import type { Metadata } from "next";
import "./globals.css";
import BottomNav from "./ui/BottomNav";
import { DMSans } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSans.className} max-w-[360px] mx-auto`}>
        <div className="bg-[#242424] min-h-dvh py-7 px-4">{children}</div>
        <div><BottomNav/></div>
      </body>
    </html>
  );
}
